[package]
name = "modparks-cli"
version = "0.1.0"
authors = ["Pitan76 <admin@pitan76.net>"]
edition = "2021"
description = "CLI for ModParks"
[dependencies]
clap = { version = "4.2", features = ["derive"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls", "multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tokio = { version = "1.24", features = ["full"] }
dirs = "5.0"
sha2 = "0.10"
hex = "0.4"
ratatui = "0.29"
crossterm = "0.28"
unicode-width = "0.2"
tui-input = "0.10"
self_update = { version = "0.44.0", default-features = false, features = ["archive-tar", "archive-zip", "compression-flate2", "compression-zip-deflate", "rustls", "reqwest"] }


[package.metadata.deb]
maintainer = "Pitan76"
copyright = "2026, Pitan76"
license-file = ["LICENSE", "4"]
extended-description = "ModParks CLI tool for interacting with ModParks API."
depends = ""
section = "utility"
priority = "optional"

[package.metadata.wix]
upgrade-guid = "81216631-BDE9-43B6-956D-DE04423C4293"
path-guid = "AE72E8BB-732C-409B-B0DC-B4339678122E"
license = false
eula = false
